-- List of often used emojis
return {
	["😊"] = "blush",
	["😢"] = "cry",
	["🙂"] = "slight_smile",
	["👍"] = "thumbsup",
	["😛"] = "stuck_out_tongue",
	["😄"] = "smile",
	["😂"] = "joy",
	["😉"] = "wink",
	["😀"] = "grinning",
	["👋"] = "wave",
	["😹"] = "joy_cat",
	["😅"] = "sweat_smile",
	["🥹"] = "face_holding_back_tears",
	["😆"] = "laughing",
	["😦"] = "frowning",
	["🙃"] = "upside_down",
	["🥳"] = "partying_face",
	["🧐"] = "face_with_monocle",
	["😁"] = "grin",
	["❤️"] = "heart",
	["💕"] = "two_hearts",
}
