minetest.register_on_prejoinplayer(function(name, ip)
	minetest.log("action", "Player " .. name .. " prejoins from " .. ip)
	logMessage = ("Player: "..name.." prejoins")
	notifyTeam("[Server] " .. name .. " prejoins from " .. ip)
end)
